name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    permissions:
      contents: write
    strategy:
      matrix:
        include:
          - os: windows-latest
            build_cmd: npm run build:win
          - os: macos-latest
            build_cmd: npm run build && npx electron-builder --mac
          - os: macos-latest
            build_cmd: npm run build && npx electron-builder --mac --x64
          - os: ubuntu-latest
            build_cmd: npm run build:linux
    runs-on: ${{ matrix.os }}
    env:
      EP_DUMMY_GITHUB_TOKEN: dummy
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      - run: ${{ matrix.build_cmd }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: softprops/action-gh-release@v2
        with:
          files: |
            release/*.exe
            release/*.dmg
            release/*.AppImage
